service: word-counter

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  analyze:
    handler: handler.handle_request
    events:
      - http:
          path: analyze
          method: post
          cors: true
    environment:
      ANTHROPIC_API_KEY: ${ssm:/anthropic/api_key} 